{
 "title": "vSphere overview",
 "tags": [ "vsphere-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(vcenter_vm_memory_usage_mebibytes{job=~\"integrations/vsphere\"}, job)"
   },
   {
    "name": "vcenter_datacenter_name",
    "label": "Datacenter",
    "query": "label_values(vcenter_vm_memory_usage_mebibytes{job=~\"integrations/vsphere\",job=~\"$job\"}, vcenter_datacenter_name)"
   },
   {
    "name": "top_resource_count",
    "label": "Top resource count",
    "query": "2 : 2,4 : 4,6 : 6,8 : 8,10 : 10"
   }
  ]
 },
 "panels": [
  {
   "title": "Metrics",
   "type": "stat",
   "description": "Shows if metrics are being received for the selected time range.",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(vcenter_cluster_name, vcenter_datacenter_name, vcenter_host_name) (vcenter_host_memory_usage_mebibytes{job=~\"$job\"}) > bool 0\n"
    }
   ]
  },
  {
   "title": "Latest metrics received",
   "type": "stat",
   "description": "Shows the timestamp of the latest metrics received for this integration in the last 24 hours.",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(vcenter_cluster_name, vcenter_datacenter_name, vcenter_host_name) (vcenter_host_memory_usage_mebibytes{job=~\"$job\"}) > bool 0\n"
    }
   ]
  },
  {
   "title": "Integration version",
   "type": "stat",
   "description": "Shows the installed version of this integration.",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Clusters",
   "type": "stat",
   "description": "The number of clusters in the datacenter.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(vcenter_cluster_name) (vcenter_cluster_vm_count{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}))"
    }
   ]
  },
  {
   "title": "ESXi hosts",
   "type": "stat",
   "description": "The number of ESXi hosts in the datacenter.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(vcenter_host_name) (vcenter_host_memory_usage_mebibytes{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}))"
    }
   ]
  },
  {
   "title": "Resource pools",
   "type": "stat",
   "description": "The number of resource pools in the datacenter.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(vcenter_resource_pool_inventory_path) (vcenter_resource_pool_cpu_shares{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}))"
    }
   ]
  },
  {
   "title": "VMs",
   "type": "stat",
   "description": "The number of virtual machines in the datacenter.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(vcenter_resource_pool_inventory_path, vcenter_virtual_app_inventory_path, vcenter_vm_name) (vcenter_vm_memory_usage_mebibytes{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}))"
    }
   ]
  },
  {
   "title": "Clustered VMs on",
   "type": "stat",
   "description": "The number of virtual machines currently powered on that belong to a cluster in the datacenter.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job, vcenter_datacenter_name) (vcenter_cluster_vm_count{power_state=\"on\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"})"
    }
   ]
  },
  {
   "title": "Clustered VMs off",
   "type": "stat",
   "description": "The number of virtual machines currently powered off that belong to a cluster in the datacenter.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job, vcenter_datacenter_name) (vcenter_cluster_vm_count{power_state=\"off\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"})"
    }
   ]
  },
  {
   "title": "Clustered VMs suspended",
   "type": "stat",
   "description": "The number of virtual machines currently in a suspended state that belong to a cluster in the datacenter.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job, vcenter_datacenter_name) (vcenter_cluster_vm_count{power_state=\"suspended\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"})"
    }
   ]
  },
  {
   "title": "Clustered VM templates",
   "type": "stat",
   "description": "The number of virtual machine templates that belong to a cluster in the datacenter.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job, vcenter_datacenter_name) (vcenter_cluster_vm_template_count{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"})"
    }
   ]
  },
  {
   "title": "Clustered active ESXi hosts",
   "type": "stat",
   "description": "The number of ESXi hosts that are currently running (responding and not in maintenance mode) that belong to a cluster within the datacenter.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job, vcenter_datacenter_name) (vcenter_cluster_host_count{effective=\"true\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"})"
    }
   ]
  },
  {
   "title": "Clustered inactive ESXi hosts",
   "type": "stat",
   "description": "The number of ESXi hosts that are currently not running (not responding or in maintenance mode) that belong to a cluster within the datacenter.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job, vcenter_datacenter_name) (vcenter_cluster_host_count{effective=\"false\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"})"
    }
   ]
  },
  { "title": "Clusters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Top CPU utilization by cluster",
   "type": "timeseries",
   "description": "The clusters with the highest CPU utilization percentage in the datacenter.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk ($top_resource_count, (100 * sum by (job, vcenter_datacenter_name, vcenter_cluster_name) (vcenter_host_cpu_usage_MHz{vcenter_cluster_name!=\"\",job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}) / clamp_min(vcenter_cluster_cpu_limit{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"},1)))",
     "legendFormat": "{{vcenter_cluster_name}}"
    }
   ]
  },
  {
   "title": "Top memory utilization by cluster",
   "type": "timeseries",
   "description": "The clusters with the highest memory utilization percentage in the datacenter.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk ($top_resource_count, (104857600 * sum by (job, vcenter_datacenter_name, vcenter_cluster_name) (vcenter_host_memory_usage_mebibytes{vcenter_cluster_name!=\"\",job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}) / clamp_min(vcenter_cluster_memory_limit_bytes{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"},1)))",
     "legendFormat": "{{vcenter_cluster_name}}"
    }
   ]
  },
  {
   "title": "Clusters table",
   "type": "table",
   "description": "Information about the clusters in the vCenter environment.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "vcenter_cluster_cpu_limit{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}",
     "legendFormat": "{{vcenter_cluster_name}}"
    },
    {
     "expr": "topk ($top_resource_count, (100 * sum by (job, vcenter_datacenter_name, vcenter_cluster_name) (vcenter_host_cpu_usage_MHz{vcenter_cluster_name!=\"\",job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}) / clamp_min(vcenter_cluster_cpu_limit{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"},1)))",
     "legendFormat": "{{vcenter_cluster_name}}"
    },
    {
     "expr": "vcenter_cluster_memory_limit_bytes{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}",
     "legendFormat": "{{vcenter_cluster_name}}"
    },
    {
     "expr": "topk ($top_resource_count, (104857600 * sum by (job, vcenter_datacenter_name, vcenter_cluster_name) (vcenter_host_memory_usage_mebibytes{vcenter_cluster_name!=\"\",job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}) / clamp_min(vcenter_cluster_memory_limit_bytes{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"},1)))",
     "legendFormat": "{{vcenter_cluster_name}}"
    },
    {
     "expr": "vcenter_cluster_host_count{effective=\"true\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}"
    },
    {
     "expr": "vcenter_cluster_host_count{effective=\"false\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}"
    },
    {
     "expr": "vcenter_cluster_vm_count{power_state=\"on\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}"
    },
    {
     "expr": "vcenter_cluster_vm_count{power_state=\"off\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}"
    },
    {
     "expr": "vcenter_cluster_vm_count{power_state=\"suspended\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}"
    }
   ]
  },
  { "title": "Resource pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Top CPU usage by resource pools",
   "type": "timeseries",
   "description": "The resource pools with the highest CPU usage in the datacenter.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    {
     "expr": "topk ($top_resource_count, vcenter_resource_pool_cpu_usage{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"})",
     "legendFormat": "{{vcenter_resource_pool_inventory_path}}"
    }
   ]
  },
  {
   "title": "Top memory usage by resource pools",
   "type": "timeseries",
   "description": "The resource pools with the highest memory usage in the datacenter.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "topk ($top_resource_count, vcenter_resource_pool_memory_usage_mebibytes{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"})",
     "legendFormat": "{{vcenter_resource_pool_inventory_path}}"
    }
   ]
  },
  {
   "title": "Top CPU shares by resource pools",
   "type": "timeseries",
   "description": "The resource pools with the highest amount of CPU shares allocated in the datacenter.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "shares" } },
   "targets": [
    {
     "expr": "topk ($top_resource_count, vcenter_resource_pool_cpu_shares{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"})",
     "legendFormat": "{{vcenter_resource_pool_inventory_path}}"
    }
   ]
  },
  {
   "title": "Top memory shares by resource pools",
   "type": "timeseries",
   "description": "The resource pools with the highest amount of memory shares allocated in the datacenter.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "shares" } },
   "targets": [
    {
     "expr": "topk ($top_resource_count, vcenter_resource_pool_memory_shares{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"})",
     "legendFormat": "{{vcenter_resource_pool_inventory_path}}"
    }
   ]
  },
  { "title": "ESXi hosts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Top CPU utilization by ESXi hosts",
   "type": "timeseries",
   "description": "The ESXi hosts with the highest CPU utilization in the datacenter.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk ($top_resource_count, vcenter_host_cpu_utilization_percent{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"})",
     "legendFormat": "{{vcenter_host_name}}"
    }
   ]
  },
  {
   "title": "Top memory utilization by ESXi hosts",
   "type": "timeseries",
   "description": "The ESXi hosts with the highest memory utilization in the datacenter.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk ($top_resource_count, vcenter_host_memory_utilization_percent{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"})",
     "legendFormat": "{{vcenter_host_name}}"
    }
   ]
  },
  {
   "title": "Top avg disk latency by ESXi hosts",
   "type": "timeseries",
   "description": "The ESXi hosts with the highest average disk latency in the datacenter.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk ($top_resource_count, sum by (job, vcenter_datacenter_name, vcenter_cluster_name, vcenter_host_name) (vcenter_host_disk_latency_avg_milliseconds{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}))",
     "legendFormat": "{{vcenter_host_name}}"
    }
   ]
  },
  {
   "title": "Top packet errors by ESXi hosts",
   "type": "timeseries",
   "description": "The ESXi hosts with the highest percentage of packet errors in the datacenter.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk ($top_resource_count, sum by (job, vcenter_datacenter_name, vcenter_cluster_name, vcenter_host_name) (vcenter_host_network_packet_error_rate{object=\"\",job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}) / clamp_min(sum by (job, vcenter_datacenter_name, vcenter_cluster_name, vcenter_host_name) (vcenter_host_network_packet_rate{object=\"\",job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}), 1))",
     "legendFormat": "{{vcenter_host_name}}"
    }
   ]
  },
  { "title": "Datastores", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Datastores table",
   "type": "table",
   "description": "Information about the datastores in the vCenter environment.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sum by (job, vcenter_datacenter_name, vcenter_datastore_name) (vcenter_datastore_disk_usage_bytes{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"})"
    },
    {
     "expr": "vcenter_datastore_disk_utilization_percent{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}"
    },
    {
     "expr": "vcenter_datastore_disk_usage_bytes{disk_state=\"available\",job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}"
    }
   ]
  }
 ]
}